agent:
  name: actrep
  class: agent.actrep.ActRepAgent
  params:
    obj_id_to_embedding_file: ../../../bomberman_obj_id_to_embedding.data
    vocab_size: 40
    state_embed_size: 10
    text_embed_size: 1024
    obs_dim: ??
    action_range: ??
    action_dim: ??
    latent_dim: 6
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    fusion_cfg: ${fusion_model}
    approxg_cfg: ${approxg}
    decoderf_cfg: ${decoderf}
    discount: 0.99
    init_temperature: 0.1
    fusion_lr: 1e-3
    fusion_betas: [0.9, 0.999]
    alpha_lr: 1e-3
    alpha_betas: [0.9, 0.999]
    actor_lr: 1e-3
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_lr: 1e-3
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 2
    approxg_lr: 1e-3
    approxg_betas: [0.9, 0.999]
    decoderf_lr: 1e-3
    decoderf_betas: [0.9, 0.999]
    batch_size: 32
    learnable_temperature: true

fusion_model:
  class: agent.fusion.Fusion
  params:
    state_embed_size: ${agent.params.state_embed_size}
    text_embed_size: ${agent.params.text_embed_size}
    vocab_size: ${agent.params.vocab_size}

approxg:
  class: agent.approx_decoder.Approximator
  params:
    fusion_dim: 288
    hidden_dim: 1024
    hidden_depth: 2
    latent_dim: ${agent.params.latent_dim}

decoderf:
  class: agent.approx_decoder.Decoder
  params:
    latent_dim: ${agent.params.latent_dim}
    hidden_dim: 1024
    hidden_depth: 2
    action_dim: ${agent.params.action_dim}

double_q_critic:
  class: agent.critic.DoubleQCritic
  params:
    fusion_dim: 288
    action_dim: ${agent.params.action_dim}
    hidden_dim: 1024
    hidden_depth: 2

diag_gaussian_actor:
  class: agent.actor.DiagGaussianActor
  params:
    fusion_dim: 288
    action_dim: ${agent.params.action_dim}
    hidden_dim: 1024
    hidden_depth: 2
    log_std_bounds: [-5, 2]
